# Generated by Django 3.2 on 2023-01-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_details',
            name='query_answered',
            field=models.BooleanField(default=False),
        ),
    ]
