# Generated by Django 3.2 on 2023-01-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contact_details_query_answered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_details',
            new_name='send_a_query',
        ),
    ]
